services:
  tsm-project:
    image: tsm-project:latest
    container_name: tsm-project
    ports:
      - 8080:8080
    env_file:
      - dev.env
    depends_on:
      - tsm_db
      - smtp

  tsm_db:
    container_name: tsm_db
    image: postgres:15-alpine
    env_file:
      - dev.env
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql
    restart: unless-stopped

  smtp:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025

